### ISSUE TITLE
Pull Request for permafrost validation notebook and utilities

### ISSUE THREAD

**Issue by ac-johnson** [nisar-solid/ATBD#47]
The remote sensing group at University of Alaska Fairbanks is submitting permafrost NISAR Cal/Val functionality this repository. Please see the corresponding Pull Request from myself.

The primary notebook is "methods/permafrost/Permafrost_Requirement_Validation.ipynb" and it follows as much of the format as the other Solid Earth validation notebooks when possible. Functions for the time series spline fitting algorithm used in this validation approach is included in "solid_utils/permafrost_utils.py"

As it is now, we use Hyp3 to produce S1 interferograms rather than ARIA as in the other Solid Earth approaches. A very short notebook is also included for users to produce and download the interferogram stack(s) used in the notebook. 

Additionally, we are providing a set of field data surface displacement observations, as measured by GNSS and surveying. That data is in the process of being added to the cal/val database. However, until it is added, the summer 2023 data is included in a small .zip file in this pull request which contains 8 short .csv files.

**Comment by dbekaert** [comment]
Reviewed and merged
