### ISSUE TITLE
Variogram

### ISSUE THREAD

**Issue by dbekaert** [nisar-solid/ATBD#8]
> ### Statistical functions for comparison
> * Deramp --> [Raider deramp](https://github.com/dbekaert/RAiDER/blob/452cc9c429a0d34831640c6926a99e456ea051dd/tools/RAiDER/statsPlot.py#L345-L348)
> * Calculate experimental variogram --> [RAiDER variogram](https://github.com/dbekaert/RAiDER/blob/452cc9c429a0d34831640c6926a99e456ea051dd/tools/RAiDER/statsPlot.py#L327-L331)
> * Calculate binned variogram with functional fitting --> [RAiDER binning](https://github.com/dbekaert/RAiDER/blob/452cc9c429a0d34831640c6926a99e456ea051dd/tools/RAiDER/statsPlot.py#L358-L386) and [RAiDER fitting](https://github.com/dbekaert/RAiDER/blob/452cc9c429a0d34831640c6926a99e456ea051dd/tools/RAiDER/statsPlot.py#L388-L450)
> * Calculate double-difference --> [RAiDER pairs](https://github.com/dbekaert/RAiDER/blob/452cc9c429a0d34831640c6926a99e456ea051dd/tools/RAiDER/statsPlot.py#L288-L308)

@cmarshak made [this repository](https://github.com/nisar-solid/variogram-sample) with @dbekaert to break out these functional components. There are few more things I need to add, but hopefully this is a clear starting point. Thanks!

**Comment by dbekaert** [comment]
@yunjunz Looking for some guidance on how you want to set up code contributions, structure etc. For now we will append to this repository.

**Comment by yunjunz** [comment]
@dbekaert since I don't expect a lot of new script development here, adding a `solid_utils` directory in the `ATBD` repo, serving as a unique module name, could be a convenient option. Of course, this root name can be changed easily afterward.

**Comment by dbekaert** [comment]
@cmarshak could you move the code per instruction above? Feel free to move the example notebook into one of the jupuyter folders.

**Comment by cmarshak** [comment]
Ok - sounds good.
